#!/usr/bin/env python3
# doi --- DOI to Sci-Hub

"""
Usage note

In order to use this script you need to have a search engine like

  c.url.searchengines['#sci'] = "https://sci-hub.se/{}"

in your config.py.  This is intended to make it easier to update the
Sci-Hub domain should it change again later.  At a later date I plan
to write a userscript or addon Aaron Janse’s ‘DNS over Wikipedia’
extension for Firefox which can look up Wikipedia to find the latest
domain of activist projects like Sci-Hub, Libgen, etc.
"""


import os
import re

fifo = open(os.getenv("QUTE_FIFO"), "w")

mode = os.getenv("QUTE_MODE")

text = None

if mode == "hints":
    text = os.getenv("QUTE_URL").strip()
elif mode == "command":
    text = os.getenv("QUTE_SELECTED_TEXT").strip()

# DOI syntax: https://www.doi.org/doi_handbook/2_Numbering.html#2.2.
#
# Note that this probably matches a subset of possible DOIs, as it
# seems that there’s no practical limitation on neither the length nor
# the contents of the DOI.  But IMHO this is a healthy subset.
doi_re = re.compile(
    # match possible URI prefix
    r"(?P<blah>((https?)?://)?doi\.org/)?"
    # match actual DOI
    r"(?P<meat>[a-zA-Z0-9\./\-_]+)"
)

match = doi_re.match(text)

if match is None:
    fifo.write(
        f"message-warning \"`{text}' is probably"
        f" not a DOI, or update regexp\""
    )

else:
    doi = match['meat']
    fifo.write(f"open -t #sci {doi}")

fifo.flush()
