#!/bin/sh
# xsessionrc --- x session environment -*- shell-script -*-

source $HOME/.profile

# Inform systemd
if [ -z "$GUIX_PROFILE" ]; then
    systemctl --user import-environment DISPLAY
    systemctl --user import-environment DESKTOP_SESSION

    # Ensure correct user dirs configuration
    xdg-user-dirs-update
fi


### X resources:
xrdb -merge $MEINE/Xdefaults

### DConf database:
dconf load / < $MYSYSTEM/dconf.dump

### Input:
#### Keyboard:
setxkbmap -option "ctrl:nocaps"

### System specific desktop setup:

if [ -e "$MYSYSTEM/desktop-setup.bash" ]; then
    case "$XDG_SESSION_TYPE" in
        # A session started with startx or my sx alias will have it
        # set like this.
        tty) exec dbus-launch --exit-with-session bash $MYSYSTEM/desktop-setup.bash ;;
        # GDM etc. sets it like this, which should do the dbus
        # housekeeping itself.
        x11) bash $MYSYSTEM/desktop-setup.bash ;;
        # A wayland session should not run this script but in case
        # that happens by accident it’s nice to have this in the logs
        # somehow.
        wayland)
            echo "$0: *** WAYLAND SESSION SETUP NOT IMPLEMENTED YET ***" ;;
        # This case should be unreachable but in case it is, it’s nice
        # to have a line in the logs.
        *) echo "$0: Unknown session type: XDG_SESSION_TYPE=$XDG_SESSION_TYPE (this shouldn't happen)" ;;
    esac
fi
