#!/bin/sh
# xsessionrc --- x session environment -*- shell-script -*-

. $HOME/.profile

# Inform systemd
if [ -z "$GUIX_PROFILE" ]; then
    systemctl --user import-environment DISPLAY
    systemctl --user import-environment DESKTOP_SESSION

    # Ensure correct user dirs configuration
    xdg-user-dirs-update
fi


### X resources:
xrdb -merge $MEINE/Xdefaults

### Input:
#### Keyboard:
setxkbmap -option "ctrl:nocaps"

### System specific desktop setup:

if [ -f "$MYSYSTEM/desktop-setup.bash" ]; then
    bash $MYSYSTEM/desktop-setup.bash
fi
