#!/bin/sh
# X session initialisation file.

set -e

# If shell settings are not loaded yet, load them.
if [ "x$SHRC_VERSION" == "x" ]; then
	echo Source user profile...
	. $HOME/.profile
fi

echo Merge X resources...
xrdb -merge $MEINE/Xdefaults

echo Set keyboard map layout to gb...
setxkbmap gb
echo Load keyboard settings...
xmodmap $MEINE/xmodmap.txt

echo xinput settings
xinput --set-prop 'ETPS/2 Elantech Touchpad' 286 1 # natural scrolling
# click method: no areas, two finger is right click, three finger middle
xinput --set-prop 'ETPS/2 Elantech Touchpad' 294 0 1

xsetroot -grey&

echo 'Start the desktop session...'
exec dbus-launch --exit-with-session $MEINE/x.sh
