#!/bin/sh
# X session initialisation file.

set -e

say () {
	echo \[$(date)\] $* >> ~/.xinit.errors
}

# If shell settings are not loaded yet, load them.
if [ "x$SHRC_VERSION" = "x" ]; then
	say Source user profile...
	. $HOME/.profile
fi

say Merge X resources...
xrdb -merge $MEINE/Xdefaults

say Keyboard settings...
setxkbmap gb basic ctrl:nocaps

say Set the background.
xsetroot -gray

say xinput settings
xinput --set-prop 'ETPS/2 Elantech Touchpad' 282 -75 -75 # natural scrolling

say Start status bar script
dwm-status.sh &

say 'Start the desktop session...'
exec dbus-launch --exit-with-session sh $MEINE/x.sh
