#!/bin/sh
# xsessionrc --- x session environment -*- shell-script -*-

. $HOME/.profile

# Inform systemd
systemctl --user import-environment DISPLAY
systemctl --user import-environment DESKTOP_SESSION

# Ensure correct user dirs configuration
xdg-user-dirs-update

### X resources:
xrdb -merge $MEINE/Xdefaults

### Input:
#### Keyboard:
setxkbmap -option "ctrl:nocaps"

