;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        eval-last-sexp
        gk-maybe-expand-abbrev-or-space
        insert-parentheses
        paredit-splice-sexp-killing-backward
        paredit-wrap-round
        ))

(setq mc/cmds-to-run-once
      '(
        ))
