;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        gk-bol
        gk-maybe-expand-abbrev-or-space
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        org-cycle
        org-self-insert-command
        ))
