# i3cheatsheet.sh --- Cheatsheet autogenerated from i3 configuration file

# From: https://news.ycombinator.com/item?id=18909446

config="$(if [ -d $HOME/.config ]; then
             echo $HOME/.config/;
          else
             echo $HOME/.;
          fi)i3/config"

xterm -T 'i3cheatsheet' -e "grep ^bind $config \
    | cut -d ' ' -f 2- | sed 's/ /\t/' | column -ts $'\t' \
    | pr -2 -w 145 -t | $PAGER"
